name: RSpec

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /home/runner/apt-cache
          key: ${{ runner.os }}-apt-unixodbc-dev

      - name: Install system dependencies
        run: |
          mkdir -p /home/runner/apt-cache
          sudo apt-get update
          sudo apt-get install -y -o Dir::Cache::Archives="/home/runner/apt-cache" unixodbc-dev
          sudo chown -R $(whoami) /home/runner/apt-cache

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
